name: Tests
on:
  push:
    branches: [ Tests ]

jobs:
  download_microsoft_edge_on_the_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Get update
        run: sudo apt-get update
      - name: Download Edge
        run: wget -P /home/runner/work "http://download1593.mediafire.com/alybzyvps6hg/hqf6y31uwx2no5b/microsoft-edge-stable_102.0.1245.33-1_amd64.deb"
      - name: List all the directory
        run: |
          cd /home/runner/work
          ls
