name: Tests
on:
  push:
    branches: [ Tests ]

jobs:
  download_microsoft_edge_on_the_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Get update
        run: apt-get update
      - name: Get sudo
        run: apt-get -y install sudo
      - name: Download Edge
        run: curl https://mega.nz/file/wEcXGD6Z#zPCX8dRPoALJkA5Yhfjn_DWmWMibqZv6Nnblzw2dPGQ
      - name: List all the directory
        run: dir

