name: Tests
on:
  push:
    branches: [ Tests ]

jobs:
  Container_setup_and_run_CCS:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Docker build and push
        uses: docker/build-push-action@v3
        
      - name: Get update
        run: sudo apt-get update
      
      - name: Download Edge
        run: wget -P /home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CCS "https://download1492.mediafire.com/rgxmcnld3phg/axbrk2frk18va0d/microsoft-edge-stable_101.0.1210.32-1_amd64.deb"

      - name: Package the app into a jar
        run: |
          cd /home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CCS
          ls
          mvn package -DskipTests
      
      - name: Create the container
        run: docker build -f Dockerfile -t docker-ccs .
          
      - name: Run container
        run: docker run --name ccs -d -p 8080:8080 docker-ccs -w /home/app
      
      - name: Set the selenium server
        run: |
          docker ps
          docker exec ccs java -jar home/app/selenium-server-4.1.4.jar hub --host 172.17.0.2 --port 4444 &
          docker exec ccs java -jar home/app/selenium-server-4.1.4.jar node --detect-drivers true --hub http://localhost:4444/grid/register &
      
      - name: Run Tests
        run: docker exec ccs mvn test --file /home/app
        
      - name: If you are here the tests went well so merge to main trunk
        run: git merge main
        
  Container_setup_and_run_CTT:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Docker build and push
        uses: docker/build-push-action@v3
        
      - name: Get update
        run: sudo apt-get update
      
      - name: Download Edge
        run: wget -P /home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CTT "https://download1492.mediafire.com/rgxmcnld3phg/axbrk2frk18va0d/microsoft-edge-stable_101.0.1210.32-1_amd64.deb"
      
      - name: Check if downloaded
        run: |
          cd /home/runner/work
          ls
          
      - name: Package the app into a jar
        run: |
          cd /home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CTT
          ls
          mvn package -DskipTests
      
      - name: Create the container
        run: docker build -f Dockerfile -t docker-ctt .
          
      - name: Run container
        run: docker run --name ctt -d -p 8080:8080 docker-ctt -w /home/app
      
      - name: Set the selenium server
        run: |
          docker ps
          docker exec ctt java -jar home/app/selenium-server-4.1.4.jar hub --host 172.17.0.2 --port 4444 &
          docker exec ctt java -jar home/app/selenium-server-4.1.4.jar node --detect-drivers true --hub http://localhost:4444/grid/register &
      
      - name: Run Tests
        run: docker exec ctt mvn test --file /home/app
        
      - name: If you are here the tests went well so merge to main trunk
        run: git merge main
