name: Tests
on:
  push:
    branches: [ Tests ]

jobs:
  download_microsoft_edge_on_the_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Get update
        run: sudo apt-get update
      - name: Download Edge
        run: curl -L https://go.microsoft.com/fwlink?linkid=2149051
      - name: List all the directory
        run: |
          cd /home/runner/work
          ls
