name: tests
on:
  push:
    branches: [ Tests ]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
          
      - name: Getting apt updates
        run: sudo apt-get update
        
      - name: Install MongoDB
        run: | 
          sudo apt-get install gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
          sudo apt-get install -y mongodb-org
        
      #- name: Setting up MongoDB on standard port
      #  uses: supercharge/mongodb-github-action@1.7.0
        
      - name: Trick from stackoverflow for letting the remote system execute mongo service
        run: |
          sudo systemctl enable mongod
          sudo systemctl daemon-reload
        
      - name: Starting MongoDB
        #run: sudo service mongod start
        run: sudo systemctl start mongod
        
      - name: Opening the mongo shell
        run: mongo
        
      - name: Creating the CCS database
        run: use CCS 
        
      - name: Adding CTT-DATA for testing
        run: db.CTT.insertMany([
          {
          "_id":{"$oid":"622c835630e4094450e59a93"},
          "denominazione":"CTT001",
          "provincia":"BN",
          "citta":"Benevento",
          "telefono":"1235468791",
          "indirizzo":"via dei test1",
          "e_mail":"test1@gmail.com",
          "latitudine":85.1,
          "longitudine":26.2
          },
          {
          "_id":{"$oid":"622c839c30e4094450e59ac3"},
          "denominazione":"CTT002",
          "provincia":"NA",
          "citta":"Napoli",
          "telefono":"3216549871",
          "indirizzo":"via dei test2",
          "e_mail":"test2@gmail.com",
          "latitudine":83.4,
          "longitudine":29.3
          },
          {
          "_id":{"$oid":"62335f29ffd9b1d1e4e6f758"},
          "denominazione":"CTT005",
          "provincia":"BN",
          "citta":"Campolattaro",
          "telefono":"0821432576",
          "indirizzo":"Via del testing 12",
          "e_mail":"CTT005@gmail.com",
          "latitudine":65,
          "longitudine":41
          }]) 

      - name: Adding DIPENDENTI-DATA for testing
        run: db.DIPENDENTI.insertMany([
          {
          "_id":{"$oid":"623340aaffd9b1d1e4e6e060"},
          "cdf":"KTMFSW67T64I460X",
          "nome":"TestAdmin",
          "cognome":"TestAdmin",
          "dataDiNascita":"1978-10-10",
          "ruolo":"AmministratoreCCS",
          "username":"admin",
          "password":"a644c646dc14f9a855fda36b5d56f0d434d6f0a878950bca47cded8b578413a6CryptoCTT"
          },
          {
          "_id":{"$oid":"62334921ffd9b1d1e4e6e647"},
          "cdf":"XDDBHH45H57H684W",
          "nome":"Pino",
          "cognome":"Perugini",
          "dataDiNascita":"2000-07-10",
          "ruolo":"AmministratoreCCS",
          "username":"username 002",
          "password":"1be0222750aaf3889ab95b5d593ba12e4ff1046474702d6b4779f4b527305b23CryptoCTT"
          },
          {
          "_id":{"$oid":"62334989ffd9b1d1e4e6e6c1"},
          "cdf":"CZGMJS46A28I333C",
          "nome":"Giovanni",
          "cognome":"Rana",
          "dataDiNascita":"1999-01-12",
          "ruolo":"AmministratoreCCS",
          "username":"username 003",
          "password":"2538f153f36161c45c3c90afaa3f9ccc5b0fa5554c7c582efe67193abb2d5202CryptoCTT"
          },
          {
          "_id":{"$oid":"623349cfffd9b1d1e4e6e6f3"},
          "cdf":"FZDTSS79C20F641W",
          "nome":"Pietro",
          "cognome":"Spini",
          "dataDiNascita":"1996-12-10",
          "ruolo":"AmministratoreCCS",
          "username":"username 004",
          "password":"db514f5b3285acaa1ad28290f5fefc38f2761a1f297b1d24f8129dd64638825dCryptoCTT"
          },
          {
          "_id":{"$oid":"62334ac2ffd9b1d1e4e6e7d7"},
          "cdf":"BVNZDG48A06D684R",
          "nome":"Gionata",
          "cognome":"Boschetto",
          "dataDiNascita":"1998-01-29",
          "ruolo":"AmministratoreCCS",
          "username":"username 005",
          "password":"8180d5783fea9f86479e748f6d2d1196c4a8e143643119398c16367d2c3d50f2CryptoCTT"
          },
          {
          "_id":{"$oid":"62334b84ffd9b1d1e4e6e8c9"},
          "cdf":"KCHXSP82M66M295O",
          "nome":"Marco",
          "cognome":"Rossi",
          "dataDiNascita":"1992-04-10",
          "ruolo":"AmministratoreCCS",
          "username":"username 006",
          "password":"75f9793a7639faa0b83a2707d60cb21c42fe9f50992fc692390a26ac2a21b29eCryptoCTT"
          },
          {
          "_id":{"$oid":"62334be9ffd9b1d1e4e6e944"},
          "cdf":"VYHBLK93H24B888J",
          "nome":"Luca",
          "cognome":"Barra",
          "dataDiNascita":"1982-10-20",
          "ruolo":"AmministratoreCCS",
          "username":"username 007",
          "password":"5bfdfaaf7e1b1244192a1ede1ea70f09f5642190821c0005669a9afbca2dee2eCryptoCTT"
          },
          {
          "_id":{"$oid":"62334c3dffd9b1d1e4e6e982"},
          "cdf":"XLFBJN93A04F885H",
          "nome":"Andrea",
          "cognome":"Rispoli",
          "dataDiNascita":"2001-12-12",
          "ruolo":"AmministratoreCCS",
          "username":"username 008",
          "password":"2ced6e7160a9e2cb4be29c200852bfc4fe29d7531ff3ffc51fc1407399d8d8b8CryptoCTT"
          },
          {
          "_id":{"$oid":"62335960ffd9b1d1e4e6f2e6"},
          "cdf":"SRNGJZ50B54C143L",
          "nome":"Ario",
          "cognome":"Lucarelli",
          "dataDiNascita":"1988-07-04",
          "ruolo":"AmministratoreCCS",
          "username":"username 123",
          "password":"1d379b64e1a7287792f4ee247929659b6af9100ef34e220ff3559b4246e45658CryptoCTT"
          },
          {
          "_id":{"$oid":"6234a2957165c224532ae635"},
          "cdf":"KTMFSW67T64I460F",
          "nome":"TestAdmin",
          "cognome":"TestAdmin",
          "dataDiNascita":"1978-10-10",
          "ruolo":"AmministratoreCCS",
          "username":"admin2",
          "password":"edaec9cbec152d167b7d42eae3a40495807656aacb15f77f60a8ca6b4a9b746eCryptoCTT"
          }])
        
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Maven clean of target dir
        run: mvn clean --file "/home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CCS"
      - name: Run CCS tests with Maven
        run: mvn test --file "/home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CCS/pom.xml"
      
      - name: Maven clean of target dir
        run: mvn clean --file "/home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CTT"
      - name: Run CTT tests with Maven
        run: mvn test --file "/home/runner/work/Ingegneria-del-software-magistrale-2022/Ingegneria-del-software-magistrale-2022/Sistema-gestione-CCS-CTT-UnaRegione-main/CTT/pom.xml"
