name: tests
on:
  push:
    branches: [ Tests ]
jobs:
  run_application:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Run springBoot application
        run: |
          cd "D:\a\Ingegneria-del-software-magistrale-2022\Ingegneria-del-software-magistrale-2022\Sistema-gestione-CCS-CTT-UnaRegione-main\CCS"
          mvn spring-boot:run
  
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
 
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
     # - name: Set inbound firewall rules
     #   run: netsh advfirewall firewall add rule name="MongoIN" dir=in action=allow protocol=TCP localport=27017
     #   
     # - name: Set outbound firewall rules
     #   run: netsh advfirewall firewall add rule name="MongoOUT" dir=out action=allow protocol=TCP localport=27017
                  
      - name: Maven clean of target dir
        run: mvn clean --file "D:\a\Ingegneria-del-software-magistrale-2022\Ingegneria-del-software-magistrale-2022\Sistema-gestione-CCS-CTT-UnaRegione-main\CCS"
      - name: Run CCS tests with Maven
        run: mvn test --file "D:\a\Ingegneria-del-software-magistrale-2022\Ingegneria-del-software-magistrale-2022\Sistema-gestione-CCS-CTT-UnaRegione-main\CCS\pom.xml"
      
      - name: Maven clean of target dir
        run: mvn clean --file "D:\a\Ingegneria-del-software-magistrale-2022\Ingegneria-del-software-magistrale-2022\Sistema-gestione-CCS-CTT-UnaRegione-main\CTT"
      - name: Run CTT tests with Maven
        run: mvn test --file "D:\a\Ingegneria-del-software-magistrale-2022\Ingegneria-del-software-magistrale-2022\Sistema-gestione-CCS-CTT-UnaRegione-main\CTT\pom.xml"
