name: Tests
on:
  push:
    branches: [ Tests ]

jobs:
  pull_and_run_containers:
    runs-on: ubuntu-latest
    steps:
      - name: Import docker Login action
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Pull the docker image for CCS
        run: docker pull francescomazzitelli/ccs:latest
      - name: Run container
        run: docker run --name docker-ccs -d -p 8080:8080 francescomazzitelli/ccs -w /home/app
      - name: Set the selenium server
        run: |
          docker ps
          docker exec docker-ccs dir
          docker exec docker-ccs java -jar home/app/selenium-server-4.1.4.jar hub --host 172.17.0.2 --port 4444
          docker exec docker-ccs java -jar home/app/selenium-server-4.1.4.jar node --detect-drivers true --hub http://localhost:4444/grid/register
      - name: Run Tests
        run: |
          docker exec cd home/app
          docker exec mvn test
          
